#!/bin/bash

cd /cromwell-executions/test/90a6e8c4-d279-4025-8bec-6cd46ab7227c/call-bye/execution
tmpDir=$(mkdir -p "/cromwell-executions/test/90a6e8c4-d279-4025-8bec-6cd46ab7227c/call-bye/tmp.0386fce0" && echo "/cromwell-executions/test/90a6e8c4-d279-4025-8bec-6cd46ab7227c/call-bye/tmp.0386fce0")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/test/90a6e8c4-d279-4025-8bec-6cd46ab7227c/call-bye/execution

)
out90a6e8c4="${tmpDir}/out.$$" err90a6e8c4="${tmpDir}/err.$$"
mkfifo "$out90a6e8c4" "$err90a6e8c4"
trap 'rm "$out90a6e8c4" "$err90a6e8c4"' EXIT
tee '/cromwell-executions/test/90a6e8c4-d279-4025-8bec-6cd46ab7227c/call-bye/execution/stdout' < "$out90a6e8c4" &
tee '/cromwell-executions/test/90a6e8c4-d279-4025-8bec-6cd46ab7227c/call-bye/execution/stderr' < "$err90a6e8c4" >&2 &
(
cd /cromwell-executions/test/90a6e8c4-d279-4025-8bec-6cd46ab7227c/call-bye/execution


echo "Bye bye Resus!"
)  > "$out90a6e8c4" 2> "$err90a6e8c4"
echo $? > /cromwell-executions/test/90a6e8c4-d279-4025-8bec-6cd46ab7227c/call-bye/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/test/90a6e8c4-d279-4025-8bec-6cd46ab7227c/call-bye/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/test/90a6e8c4-d279-4025-8bec-6cd46ab7227c/call-bye/execution
sync


)
mv /cromwell-executions/test/90a6e8c4-d279-4025-8bec-6cd46ab7227c/call-bye/execution/rc.tmp /cromwell-executions/test/90a6e8c4-d279-4025-8bec-6cd46ab7227c/call-bye/execution/rc
